# Generated by Django 3.0.8 on 2020-07-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
