# Generated by Django 3.0.8 on 2020-07-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_wishlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
